# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rcm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trcm.proto\x12\x02pb\")\n\x0b\x42ookRequest\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x03\"\x99\x01\n\x05\x42ooks\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\r\n\x05image\x18\x05 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x06 \x01(\t\x12\x11\n\tpublisher\x18\x07 \x01(\t\x12\x10\n\x08quantity\x18\x08 \x01(\x05\x12\x0e\n\x06rating\x18\t \x01(\x02\"(\n\x0c\x42ookResponse\x12\x18\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\t.pb.Books2H\n\rBookRecommend\x12\x37\n\x10GetBookRecommend\x12\x0f.pb.BookRequest\x1a\x10.pb.BookResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rcm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOOKREQUEST']._serialized_start=17
  _globals['_BOOKREQUEST']._serialized_end=58
  _globals['_BOOKS']._serialized_start=61
  _globals['_BOOKS']._serialized_end=214
  _globals['_BOOKRESPONSE']._serialized_start=216
  _globals['_BOOKRESPONSE']._serialized_end=256
  _globals['_BOOKRECOMMEND']._serialized_start=258
  _globals['_BOOKRECOMMEND']._serialized_end=330
# @@protoc_insertion_point(module_scope)
