# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.24.0
import dataclasses
import datetime
from typing import List


@dataclasses.dataclass()
class Book:
    id: int
    name: str
    price: float
    image: List[str]
    description: str
    author: str
    publisher: str
    publication_date: str
    page: str
    product_dimensions: str
    quantity: int
    is_deleted: bool
    created_at: datetime.datetime


@dataclasses.dataclass()
class BooksGenre:
    id: int
    books_id: int
    genres_id: int
    created_at: datetime.datetime


@dataclasses.dataclass()
class Genre:
    id: int
    name: str
    is_deleted: bool
    created_at: datetime.datetime


@dataclasses.dataclass()
class Review:
    id: int
    username: str
    books_id: int
    liked: int
    disliked: int
    reported: bool
    comments: str
    is_deleted: bool
    rating: int
    created_at: datetime.datetime


@dataclasses.dataclass()
class User:
    username: str
    full_name: str
    email: str
    password: str
    image: str
    phone_number: str
    age: int
    sex: str
    role: str
    is_deleted: bool
    password_changed_at: datetime.datetime
    created_at: datetime.datetime
